# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Doge4Water

# Short description (goes below the title; it will also be used in the RSS feed)
description: This is the Doge4Water website.

goal: 40000

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://doge4water.org/

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty